# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f4bcb01b31f44d47909547176842e967332991238298918346f91362970dc5f460d45d873bcee02e506de99723ddab069d9ddf9941afc7a89fbc26ff831eeee

test:
  secret_key_base: 4144f2e946b760514433b32d299985705481132084b3b4dab0b074e11742b7c35e81c19947b93ada5557e588dd2e302fc6e28f6a74de5d61e5c2f67afffff796

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
